name: "github pages deployment"

# Run workflow on every push to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: "Checkout code"
        uses: actions/checkout@v4

      # Setup .NET environment
      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'  # Specify the .NET version you want to use

      # Install WebAssembly build tools for Blazor
      - name: "Install .NET WASM Build Tools"
        run: dotnet workload install wasm-tools

      # Publish the Blazor project
      - name: "Publish Blazor WASM Project"
        run: dotnet publish ./Src/X3Code.Tools/X3Code.Tools.csproj -c Release -o dist/Web

      # Deploy to GitHub Pages
      - name: "Deploy to GitHub Pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/Web
